name: Terraform CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - azure/modules/terraform/compute
          - azure/modules/terraform/networking

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ^1.1

    - name: Run Terraform Tests
      run: |
        cd ${{ matrix.folder }}
        terraform init
        terraform validate
        terraform fmt -check
