name: Terraform Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ^1.1

    - name: Run Terraform Tests
      run: |
        {{#folders}}
        - name: "Run Terraform Tests - {{folder}}"
          run: |
            cd {{folder}}
            terraform init
            terraform validate
            terraform fmt -check
        {{/folders}}
