name: Terraform CI

on:
  push:
  merge_group:
    types: [checks_requested]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ^1.1

      - name: Run Terraform Tests
        run: |
          find . -type d -name "terraform" -execdir sh -c '
            folder=$(dirname "$1")
            cd "$folder"
            terraform init
            terraform validate
            terraform fmt -check
          ' sh {} \;
