name: Terraform CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ^1.1

    - name: Find Terraform Folders
      id: find_folders
      run: |
        echo "::set-output name=folders::$(find azure/modules/terraform -type d -name '*.tf' -exec dirname {} \; | sort -u)"

    - name: Run Terraform Tests
      run: |
        for folder in ${{ steps.find_folders.outputs.folders }}; do
          cd "$folder"
          terraform init
          terraform validate
          terraform fmt -check
          cd -
        done
